#!/usr/bin/env python3
"""
Generate openHAB text configuration for the topics this bridge publishes.

Usage:

    python -m tools.generate_openhab_config
    python -m tools.generate_openhab_config --broker mqtt-vloud --output-dir openhab
    python -m tools.generate_openhab_config --expose-installer

Copy the results into your openHAB conf folders:

    openhab/things/renson.things    -> $OPENHAB_CONF/things/
    openhab/items/renson.items      -> $OPENHAB_CONF/items/
    openhab/sitemaps/renson.sitemap -> $OPENHAB_CONF/sitemaps/

The generated Thing expects an existing MQTT broker Bridge; pass its UID with
--broker (default: mqtt).
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.topics import FILTER_RESET, command_topic, state_topic
from shared.fields import FIELDS, controllable

# unit -> (openHAB item type, channel unit). openHAB has no dimension for rpm,
# so those stay plain Numbers with no unit.
UNITS = {
    "degC": ("Number:Temperature", "°C"),
    "%": ("Number:Dimensionless", "%"),
    "ppm": ("Number:Dimensionless", "ppm"),
    "m3/h": ("Number:VolumetricFlowRate", "m³/h"),
    "V": ("Number:ElectricPotential", "V"),
    "d": ("Number:Time", "d"),
    "min": ("Number:Time", "min"),
    "rpm": ("Number", None),
    "": ("Number", None),
}

CATEGORY_LABELS = {
    "airflow": "Airflow and fans",
    "airquality": "Air quality",
    "breeze": "Breeze",
    "climate": "Climate",
    "device": "Device info",
    "diagnostics": "Diagnostics",
    "exchanger": "Heat exchanger",
    "filter": "Filter",
    "fireplace": "Fireplace",
    "io": "Input / output contacts",
    "schedule": "Day / night schedule",
    "ventilation": "Ventilation",
}

CATEGORY_ICONS = {
    "airflow": "fan",
    "airquality": "carbondioxide",
    "breeze": "wind",
    "climate": "temperature",
    "device": "text",
    "diagnostics": "error",
    "exchanger": "heating",
    "filter": "filter",
    "fireplace": "fire",
    "io": "switch",
    "schedule": "time",
    "ventilation": "fan",
}

ICONS = {
    "degC": "temperature",
    "%": "humidity",
    "ppm": "carbondioxide",
    "d": "time",
    "min": "time",
}

HEADER = "// Generated by tools/generate_openhab_config.py - safe to hand-edit.\n"


def camel_case(slug):
    return "".join(part.capitalize() for part in slug.split("_") if part)


def item_name(slug):
    return f"Renson{camel_case(slug)}"


def selected_fields(expose_installer, controls=True):
    # Mirrors CONTROLS_ENABLED: with controls off, emit state-only channels so
    # openHAB never shows a command widget the bridge would refuse.
    writable = {f.slug for f in controllable(expose_installer)} if controls else set()
    fields = [f for f in FIELDS if f.control != "blocked"]
    if not expose_installer:
        fields = [f for f in fields if f.control != "installer"]
    return fields, writable


def channel_for(field, base_topic, writable):
    state = state_topic(base_topic, field)
    command = command_topic(base_topic, field.slug)
    label = field.label

    if field.kind == "bool":
        if writable:
            return (f'Type switch : {field.slug} "{label}" '
                    f'[ stateTopic="{state}", commandTopic="{command}", on="ON", off="OFF" ]')
        return f'Type contact : {field.slug} "{label}" [ stateTopic="{state}", on="ON", off="OFF" ]'

    if field.kind in ("string", "time", "enum"):
        if writable:
            return (f'Type string : {field.slug} "{label}" '
                    f'[ stateTopic="{state}", commandTopic="{command}" ]')
        return f'Type string : {field.slug} "{label}" [ stateTopic="{state}" ]'

    _, unit = UNITS.get(field.unit, ("Number", None))
    parts = [f'stateTopic="{state}"']
    if writable:
        parts.append(f'commandTopic="{command}"')
    if unit:
        parts.append(f'unit="{unit}"')
    return f'Type number : {field.slug} "{label}" [ {", ".join(parts)} ]'


def item_for(field, thing_uid, writable):
    if field.kind == "bool":
        item_type = "Switch" if writable else "Contact"
    elif field.kind in ("string", "time", "enum"):
        item_type = "String"
    else:
        item_type, unit = UNITS.get(field.unit, ("Number", None))

    icon = ICONS.get(field.unit, CATEGORY_ICONS.get(field.category, "text"))
    group = f"gRenson{camel_case(field.category)}"
    pattern = ""
    if item_type.startswith("Number") and field.unit:
        _, unit = UNITS.get(field.unit, ("Number", None))
        if unit:
            pattern = ' [%.1f %unit%]' if field.unit == "degC" else ' [%.0f %unit%]'

    return (f'{item_type} {item_name(field.slug)} "{field.label}{pattern}" <{icon}> '
            f'({group}) {{ channel="{thing_uid}:{field.slug}" }}')


def build_things(base_topic, broker, thing_uid, fields, writable):
    lines = [HEADER,
             f"// Expects an existing MQTT broker Bridge with the UID mqtt:broker:{broker}.\n\n",
             f'Thing mqtt:topic:{broker}:renson "Renson Endura Delta" '
             f'(mqtt:broker:{broker}) @ "Ventilation" {{\n',
             "    Channels:\n",
             f'        Type string : availability "Availability" [ stateTopic="{base_topic}/status" ]\n',
             f'        Type datetime : last_success "Last successful poll" '
             f'[ stateTopic="{base_topic}/status/last_success" ]\n',
             f'        Type number : consecutive_failures "Consecutive failures" '
             f'[ stateTopic="{base_topic}/status/consecutive_failures" ]\n',
             f'        Type string : device_errors "Device errors" '
             f'[ stateTopic="{base_topic}/diagnostics/errors" ]\n',
             f'        Type contact : error_active "Error active" '
             f'[ stateTopic="{base_topic}/diagnostics/error_active", on="ON", off="OFF" ]\n',
             f'        Type contact : fire_alarm "Fire alarm" '
             f'[ stateTopic="{base_topic}/fire/alarm", on="ON", off="OFF" ]\n',
             f'        Type contact : fire_stop_confirmed "Fire stop confirmed" '
             f'[ stateTopic="{base_topic}/fire/stop_confirmed", on="ON", off="OFF" ]\n',
             ]
    if writable:
        lines.append("\n        // Filter reset button: sending any payload resets the counter.\n")
        lines.append(f'        Type switch : {FILTER_RESET} "Filter reset" '
                     f'[ commandTopic="{command_topic(base_topic, FILTER_RESET)}", on="PRESS", off="PRESS" ]\n')

    by_category = {}
    for field in fields:
        by_category.setdefault(field.category, []).append(field)

    for category in sorted(by_category):
        lines.append(f"\n        // {CATEGORY_LABELS.get(category, category)}\n")
        for field in by_category[category]:
            lines.append(f"        {channel_for(field, base_topic, field.slug in writable)}\n")

    lines.append("}\n")
    return "".join(lines)


def build_items(thing_uid, fields, writable):
    categories = sorted({f.category for f in fields})
    lines = [HEADER, "\n"]
    lines.append('Group gRenson "Renson Endura Delta" <fan>\n')
    for category in categories:
        label = CATEGORY_LABELS.get(category, category)
        icon = CATEGORY_ICONS.get(category, "text")
        lines.append(f'Group gRenson{camel_case(category)} "{label}" <{icon}> (gRenson)\n')

    lines.append('\nGroup gRensonStatus "Bridge status" <text> (gRenson)\n')
    lines.append(f'String RensonAvailability "Availability" <text> (gRensonStatus) '
                 f'{{ channel="{thing_uid}:availability" }}\n')
    lines.append(f'DateTime RensonLastSuccess "Last successful poll [%1$tF %1$tR]" <time> '
                 f'(gRensonStatus) {{ channel="{thing_uid}:last_success" }}\n')
    lines.append(f'Number RensonConsecutiveFailures "Consecutive failures" <error> '
                 f'(gRensonStatus) {{ channel="{thing_uid}:consecutive_failures" }}\n')
    lines.append(f'String RensonDeviceErrors "Device errors" <error> (gRensonStatus) '
                 f'{{ channel="{thing_uid}:device_errors" }}\n')
    lines.append(f'Contact RensonErrorActive "Error active" <error> (gRensonStatus) '
                 f'{{ channel="{thing_uid}:error_active" }}\n')
    lines.append(f'Contact RensonFireAlarm "Fire alarm" <fire> (gRensonStatus) '
                 f'{{ channel="{thing_uid}:fire_alarm" }}\n')
    lines.append(f'Contact RensonFireStopConfirmed "Fire stop confirmed" <fire> (gRensonStatus) '
                 f'{{ channel="{thing_uid}:fire_stop_confirmed" }}\n')
    if writable:
        # autoupdate="false" keeps the button from latching: it is a stateless press.
        lines.append(f'\nSwitch RensonFilterReset "Filter reset" <filter> (gRensonFilter) '
                     f'{{ channel="{thing_uid}:{FILTER_RESET}", autoupdate="false" }}\n')

    by_category = {}
    for field in fields:
        by_category.setdefault(field.category, []).append(field)

    for category in sorted(by_category):
        lines.append(f"\n// {CATEGORY_LABELS.get(category, category)}\n")
        for field in by_category[category]:
            lines.append(item_for(field, thing_uid, field.slug in writable) + "\n")

    return "".join(lines)


def build_sitemap(fields, writable):
    lines = [HEADER, '\nsitemap renson label="Ventilation" {\n']
    lines.append('    Frame label="Status" {\n')
    lines.append('        Text item=RensonAvailability\n')
    lines.append('        Text item=RensonLastSuccess\n')
    lines.append('        Text item=RensonDeviceErrors\n')
    lines.append('        Text item=RensonFireAlarm\n')
    lines.append('    }\n')
    if writable:
        lines.append('    Frame label="Filter" {\n')
        lines.append('        Switch item=RensonFilterReset mappings=[ON="Reset"]\n')
        lines.append('    }\n')

    controls = [f for f in fields if f.slug in writable]
    if controls:
        lines.append('    Frame label="Controls" {\n')
        for field in controls:
            if field.kind == "enum":
                mappings = ", ".join(f'{option}="{option}"' for option in field.options or [])
                lines.append(f'        Selection item={item_name(field.slug)} mappings=[{mappings}]\n')
            elif field.kind == "bool":
                lines.append(f'        Switch item={item_name(field.slug)}\n')
            else:
                lines.append(f'        Setpoint item={item_name(field.slug)}\n'
                             if field.minimum is not None and field.maximum is not None
                             else f'        Text item={item_name(field.slug)}\n')
        lines.append('    }\n')

    by_category = {}
    for field in fields:
        by_category.setdefault(field.category, []).append(field)
    for category in sorted(by_category):
        label = CATEGORY_LABELS.get(category, category)
        lines.append(f'    Frame label="{label}" {{\n')
        lines.append(f'        Group item=gRenson{camel_case(category)}\n')
        lines.append('    }\n')

    lines.append('}\n')
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--base-topic", default="home/ventilation/renson",
                        help="MQTT base topic the bridge publishes to")
    parser.add_argument("--broker", default="mqtt",
                        help="UID of the existing openHAB MQTT broker Bridge")
    parser.add_argument("--output-dir", default="openhab")
    parser.add_argument("--expose-installer", action="store_true",
                        help="Also emit the commissioning fields as controls")
    parser.add_argument("--no-controls", action="store_true",
                        help="State only, no command topics (matches CONTROLS_ENABLED=false)")
    args = parser.parse_args()

    base_topic = args.base_topic.rstrip("/")
    thing_uid = f"mqtt:topic:{args.broker}:renson"
    fields, writable = selected_fields(args.expose_installer, controls=not args.no_controls)

    output_dir = Path(args.output_dir)
    targets = {
        output_dir / "things" / "renson.things": build_things(base_topic, args.broker, thing_uid, fields, writable),
        output_dir / "items" / "renson.items": build_items(thing_uid, fields, writable),
        output_dir / "sitemaps" / "renson.sitemap": build_sitemap(fields, writable),
    }
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")

    print(f"\n{len(fields)} fields, {len(writable)} exposed as controls, "
          f"base topic {base_topic}")


if __name__ == "__main__":
    main()
